version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo-back3
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: entrega-back3
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mock-db

volumes:
  mongo_data:
